clear; 
close all; 
clc;

% Satellite FIS
fis_obj = newfis('satellite','AndMethod','min','AggregationMethod','max', 'DefuzzificationMethod','customdefuzz','ImplicationMethod','prod'); 

fis_obj = addvar(fis_obj, 'input', 'E', [-1 1]);
fis_obj = addvar(fis_obj, 'input', 'CE', [-1 1]);
fis_obj = addvar(fis_obj, 'output', 'CU', [-1 1]);

% Plot of Error (E)
fis_obj = addmf(fis_obj, 'input', 1, 'NL', 'trimf', [-1 -1 -0.67]);
fis_obj = addmf(fis_obj, 'input', 1, 'NM', 'trimf', [-1 -0.67 -0.33]);
fis_obj = addmf(fis_obj, 'input', 1, 'NS', 'trimf', [-0.67 -0.33 0]);
fis_obj = addmf(fis_obj, 'input', 1, 'ZR', 'trimf', [-0.33 0 0.33]);
fis_obj = addmf(fis_obj, 'input', 1, 'PS', 'trimf', [0 0.33 0.67]);
fis_obj = addmf(fis_obj, 'input', 1, 'PM', 'trimf', [0.33 0.67 1]);
fis_obj = addmf(fis_obj, 'input', 1, 'PL', 'trimf', [0.67 1 1]);

% Plot of Change of Error (CE)
fis_obj = addmf(fis_obj, 'input', 2, 'NV', 'trimf', [-1 -1 -0.75]);
fis_obj = addmf(fis_obj, 'input', 2, 'NL', 'trimf', [-1 -0.75 -0.5]);
fis_obj = addmf(fis_obj, 'input', 2, 'NM', 'trimf', [-0.75 -0.5 -0.25]);
fis_obj = addmf(fis_obj, 'input', 2, 'NS', 'trimf', [-0.5 -0.25 0]);
fis_obj = addmf(fis_obj, 'input', 2, 'ZR', 'trimf', [-0.25 0 0.25]);
fis_obj = addmf(fis_obj, 'input', 2, 'PS', 'trimf', [0 0.25 0.5]);
fis_obj = addmf(fis_obj, 'input', 2, 'PM', 'trimf', [0.25 0.5 0.75]);
fis_obj = addmf(fis_obj, 'input', 2, 'PL', 'trimf', [0.5 0.75 1]);
fis_obj = addmf(fis_obj, 'input', 2, 'PV', 'trimf', [0.75 1 1]);

% Plot of Change of U - CU
fis_obj = addmf(fis_obj, 'output', 1, 'NV', 'trimf', [-1 -1 -0.75]);
fis_obj = addmf(fis_obj, 'output', 1, 'NL', 'trimf', [-1 -0.75 -0.5]);
fis_obj = addmf(fis_obj, 'output', 1, 'NM', 'trimf', [-0.75 -0.5 -0.25]);
fis_obj = addmf(fis_obj, 'output', 1, 'NS', 'trimf', [-0.5 -0.25 0]);
fis_obj = addmf(fis_obj, 'output', 1, 'ZR', 'trimf', [-0.25 0 0.25]);
fis_obj = addmf(fis_obj, 'output', 1, 'PS', 'trimf', [0 0.25 0.5]);
fis_obj = addmf(fis_obj, 'output', 1, 'PM', 'trimf', [0.25 0.5 0.75]);
fis_obj = addmf(fis_obj, 'output', 1, 'PL', 'trimf', [0.5 0.75 1]);
fis_obj = addmf(fis_obj, 'output', 1, 'PV', 'trimf', [0.75 1 1]);

% Add rules: 7 x 9 = 63 rules (Error -> 7, Change of Error -> 9)
rules = [...
"E==NL & CE==PV => CU=PS"; ...
"E==NL & CE==PL => CU=ZR"; ...
"E==NL & CE==PM => CU=NS"; ...
"E==NL & CE==PS => CU=NM"; ...
"E==NL & CE==ZR => CU=NL"; ...
"E==NL & CE==NS => CU=NV"; ...
"E==NL & CE==NM => CU=NV"; ...
"E==NL & CE==NL => CU=NV"; ...
"E==NL & CE==NV => CU=NV"; ...
"E==NM & CE==PV => CU=PM"; ...
"E==NM & CE==PL => CU=PS"; ...
"E==NM & CE==PM => CU=ZR"; ...
"E==NM & CE==PS => CU=NS"; ...
"E==NM & CE==ZR => CU=NM"; ...
"E==NM & CE==NS => CU=NL"; ...
"E==NM & CE==NM => CU=NV"; ...
"E==NM & CE==NL => CU=NV"; ...
"E==NM & CE==NV => CU=NV"; ...
"E==NS & CE==PV => CU=PL"; ...
"E==NS & CE==PL => CU=PM"; ...
"E==NS & CE==PM => CU=PS"; ...
"E==NS & CE==PS => CU=ZR"; ...
"E==NS & CE==ZR => CU=NS"; ...
"E==NS & CE==NS => CU=NM"; ...
"E==NS & CE==NM => CU=NL"; ...
"E==NS & CE==NL => CU=NV"; ...
"E==NS & CE==NV => CU=NV"; ...
"E==ZR & CE==PV => CU=PV"; ...
"E==ZR & CE==PL => CU=PL"; ...
"E==ZR & CE==PM => CU=PM"; ...
"E==ZR & CE==PS => CU=PS"; ...
"E==ZR & CE==ZR => CU=ZR"; ...
"E==ZR & CE==NS => CU=NS"; ...
"E==ZR & CE==NM => CU=NM"; ...
"E==ZR & CE==NL => CU=NL"; ...
"E==ZR & CE==NV => CU=NV"; ...
"E==PS & CE==PV => CU=PV"; ...
"E==PS & CE==PL => CU=PV"; ...
"E==PS & CE==PM => CU=PL"; ...
"E==PS & CE==PS => CU=PM"; ...
"E==PS & CE==ZR => CU=PS"; ...
"E==PS & CE==NS => CU=ZR"; ...
"E==PS & CE==NM => CU=NS"; ...
"E==PS & CE==NL => CU=NM"; ...
"E==PS & CE==NV => CU=NL"; ...
"E==PM & CE==PV => CU=PV"; ...
"E==PM & CE==PL => CU=PV"; ...
"E==PM & CE==PM => CU=PV"; ...
"E==PM & CE==PS => CU=PL"; ...
"E==PM & CE==ZR => CU=PM"; ...
"E==PM & CE==NS => CU=PS"; ...
"E==PM & CE==NM => CU=ZR"; ...
"E==PM & CE==NL => CU=NS"; ...
"E==PM & CE==NV => CU=NM"; ...
"E==PL & CE==PV => CU=PV"; ...
"E==PL & CE==PL => CU=PV"; ...
"E==PL & CE==PM => CU=PV"; ...
"E==PL & CE==PS => CU=PV"; ...
"E==PL & CE==ZR => CU=PL"; ...
"E==PL & CE==NS => CU=PM"; ...
"E==PL & CE==NM => CU=PS"; ...
"E==PL & CE==NL => CU=ZR"; ...
"E==PL & CE==NV => CU=NS"; ...
];
fis_obj = addRule(fis_obj,rules);
writefis(fis_obj,'satellite.fis_obj')

% Plot for membership function
figure; plotfis(fis_obj)
figure; plotmf(fis_obj,'input',1)
figure; plotmf(fis_obj,'input',2)
figure; plotmf(fis_obj,'output',1)
figure; gensurf(fis_obj) %3D Plot Error(E), Change of Error(CE), Change of U(CU)

ruleview(fis_obj)